In [1]:
import numpy as np


In [6]:
# Create a 1-D array and display the data type of the array. 
array1=np.array([1,2,3,4 ,5])
array1

array([1, 2, 3, 4, 5])

In [13]:
# Create two 2D-arrays of the same shape and perform arithmetic operation on their elements. 
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
#addition
addition=ar1+ar2
print("addition:\n",addition)

addition:
 [[ 6  8 10]
 [12 14 16]]


In [14]:
subtraction=ar1-ar2
print("subtraction:\n",subtraction)

subtraction:
 [[-4 -4 -4]
 [-4 -4 -4]]


In [15]:
multiplication=ar1*ar2
print("multiplication:\n",multiplication)

multiplication:
 [[ 5 12 21]
 [32 45 60]]


In [16]:
division=ar1/ar2
print("division:\n", division)

division:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [17]:
power=np.power(ar1,ar2)
print("power:\n",power)

power:
 [[       1       64     2187]
 [   65536  1953125 60466176]]


In [23]:
# Concatenate the above 2D-arrays along rows or columns and display the result. 
con = np.concatenate([ar1,ar2])
print(con)

[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]


In [25]:
#Convert the concatenated array into a 1D-Array and display it.
flat = con.flatten()
print(flat)

[ 1  2  3  4  5  6  5  6  7  8  9 10]
