In [1]:
import numpy as np

# Create a 2x4 array of zeros
zeros_array = np.zeros((2, 4))
print("2x4 Array of Zeros:\n", zeros_array)

2x4 Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
# Create a 4x2 array of ones
ones_array = np.ones((4, 2))
print("\n4x2 Array of Ones:\n", ones_array)


4x2 Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# Print shape, dimensions, and data type of both arrays
print("Zeros Array - Shape:", zeros_array.shape, ", Dimensions:", zeros_array.ndim, ", DataType:", zeros_array.dtype)
print("Ones Array - Shape:", ones_array.shape, ", Dimensions:", ones_array.ndim, ", DataType:", ones_array.dtype)


Zeros Array - Shape: (2, 4) , Dimensions: 2 , DataType: float64
Ones Array - Shape: (4, 2) , Dimensions: 2 , DataType: float64


In [5]:
# Convert 4x2 array of ones into 1D array
ones_flat = ones_array.flatten()
print("\n1D version of 4x2 Ones Array:\n", ones_flat)


1D version of 4x2 Ones Array:
 [1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# Reshape into a different valid shape (e.g., 2x4)
reshaped = ones_flat.reshape((2, 4))
print("\nReshaped to 2x4:\n", reshaped)


Reshaped to 2x4:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Create a 4D array (e.g., shape 2x1x2x2)
array_4d = np.array([[[[1, 2], [3, 4]]], [[[5, 6], [7, 8]]]])
print("\n4D Array:\n", array_4d)


4D Array:
 [[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]


In [8]:
# Convert its elements to float
array_4d_float = array_4d.astype(float)
print("\n4D Array with Float Type:\n", array_4d_float)


4D Array with Float Type:
 [[[[1. 2.]
   [3. 4.]]]


 [[[5. 6.]
   [7. 8.]]]]
